INSERT INTO `livre` (`libelle`) VALUES ("GenÃ¨se");
INSERT INTO `livre` (`libelle`) VALUES (" Exode");
INSERT INTO `livre` (`libelle`) VALUES (" LÃ©vitique");
INSERT INTO `livre` (`libelle`) VALUES (" Nombres");
INSERT INTO `livre` (`libelle`) VALUES (" Deuteuronome");
INSERT INTO `livre` (`libelle`) VALUES (" JosuÃ©");
INSERT INTO `livre` (`libelle`) VALUES (" Juges");
INSERT INTO `livre` (`libelle`) VALUES (" Ruth");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Samuel");
INSERT INTO `livre` (`libelle`) VALUES (" 2 Samuel");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Rois");
INSERT INTO `livre` (`libelle`) VALUES (" 2 Rois");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Chroniques");
INSERT INTO `livre` (`libelle`) VALUES (" 2 Chroniques");
INSERT INTO `livre` (`libelle`) VALUES (" NÃ©hemie");
INSERT INTO `livre` (`libelle`) VALUES (" Esdras");
INSERT INTO `livre` (`libelle`) VALUES (" Job");
INSERT INTO `livre` (`libelle`) VALUES (" Psaumes");
INSERT INTO `livre` (`libelle`) VALUES (" Proverbes");
INSERT INTO `livre` (`libelle`) VALUES (" Cantiques des cantiques");
INSERT INTO `livre` (`libelle`) VALUES (" Esaie");
INSERT INTO `livre` (`libelle`) VALUES (" JÃ©rÃ©mie");
INSERT INTO `livre` (`libelle`) VALUES (" Lamentations");
INSERT INTO `livre` (`libelle`) VALUES (" Ezekiel");
INSERT INTO `livre` (`libelle`) VALUES (" Daniel");
INSERT INTO `livre` (`libelle`) VALUES (" OsÃ©e");

INSERT INTO `livre` (`libelle`) VALUES (" 2 pierre");
INSERT INTO `livre` (`libelle`) VALUES (" Jean");
INSERT INTO `livre` (`libelle`) VALUES (" Zacharie");
INSERT INTO `livre` (`libelle`) VALUES (" 2 Thessaloniciens");
INSERT INTO `livre` (`libelle`) VALUES (" AggÃ©e");
INSERT INTO `livre` (`libelle`) VALUES (" Amos");
INSERT INTO `livre` (`libelle`) VALUES (" 3 Jean");
INSERT INTO `livre` (`libelle`) VALUES (" Romains");
INSERT INTO `livre` (`libelle`) VALUES (" Zacharie");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Corinthiens");
INSERT INTO `livre` (`libelle`) VALUES (" OsÃ©e");
INSERT INTO `livre` (`libelle`) VALUES (" Luc");
INSERT INTO `livre` (`libelle`) VALUES (" 2 Chroniques");
INSERT INTO `livre` (`libelle`) VALUES (" Actes des Apotres");

INSERT INTO `livre` (`libelle`) VALUES (" Luc");
INSERT INTO `livre` (`libelle`) VALUES (" Hebreux");
INSERT INTO `livre` (`libelle`) VALUES (" 2 Samuel");
INSERT INTO `livre` (`libelle`) VALUES (" OsÃ©e");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Pierre");
INSERT INTO `livre` (`libelle`) VALUES (" MichÃ©e");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Jean");
INSERT INTO `livre` (`libelle`) VALUES (" Abacuc");
INSERT INTO `livre` (`libelle`) VALUES (" Luc");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Thessaloniciens");
INSERT INTO `livre` (`libelle`) VALUES (" Daniel");
INSERT INTO `livre` (`libelle`) VALUES (" Tites");
INSERT INTO `livre` (`libelle`) VALUES (" Ephesiens");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Jean");
INSERT INTO `livre` (`libelle`) VALUES (" OsÃ©e");
INSERT INTO `livre` (`libelle`) VALUES (" Zacharie");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Chroniques");
INSERT INTO `livre` (`libelle`) VALUES (" 2 Thessaloniciens");
INSERT INTO `livre` (`libelle`) VALUES (" 1 TimothÃ©e");
INSERT INTO `livre` (`libelle`) VALUES (" 1 Pierre");
INSERT INTO `livre` (`libelle`) VALUES (" Exode");
INSERT INTO `livre` (`libelle`) VALUES (" Tites");
INSERT INTO `livre` (`libelle`) VALUES (" Abacuc");
INSERT INTO `livre` (`libelle`) VALUES (" MichÃ©e");
INSERT INTO `livre` (`libelle`) VALUES (" Marc");
INSERT INTO `livre` (`libelle`) VALUES (" Joel");
INSERT INTO `livre` (`libelle`) VALUES (" MichÃ©e");
INSERT INTO `livre` (`libelle`) VALUES (" JÃ©rÃ©mie");
INSERT INTO `livre` (`libelle`) VALUES (" 2 Samuel");